import { NextResponse } from "next/server";
import jsPDF from "jspdf";

export async function GET() {
  try {
    const pdf = new jsPDF("p", "mm", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();

    // Add some test content
    pdf.setFontSize(24);
    pdf.setFont("helvetica", "bold");
    pdf.setTextColor(59, 130, 246);
    pdf.text("Test PDF Generation", pageWidth / 2, 30, { align: "center" });

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.setTextColor(107, 114, 128);
    pdf.text("This is a test PDF generated by jsPDF", 20, 50);
    pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 60);

    // Convert to base64
    const pdfBase64 = pdf.output("datauristring");

    return NextResponse.json({
      success: true,
      message: "Test PDF generated successfully",
      pdfData: {
        base64: pdfBase64,
        filename: `test-pdf-${new Date().toISOString().split("T")[0]}.pdf`,
      },
    });
  } catch (error) {
    console.error("Test PDF generation error:", error);
    return NextResponse.json(
      { error: "PDF generation failed", details: error.message },
      { status: 500 }
    );
  }
}
